name: Run Tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get access to repo
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
      - name: Run test
        run: npm run test
  lint:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Get access to repo
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
      - name: Run linter
        run: npm run lint
  deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get access to repo
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
      - name: Build app
        run: npm run build